"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { createSupplierAllocation } from "@/lib/supplier-allocations/actions";
import { getActiveSupplierRateCardsForAllocation } from "@/lib/suppliers/rate-card-actions";
import type { SupplierOption } from "@/lib/suppliers/types";
import type { SupplierRateCard } from "@/lib/suppliers/rate-card-types";

type CostSource = "manual_estimate" | "rate_card";

export default function SupplierAllocationCreateForm({
  serviceId,
  suppliers,
  canUseRateCards = false,
}: {
  serviceId: string;
  suppliers: SupplierOption[];
  canUseRateCards?: boolean;
}) {
  const router = useRouter();
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  
  const [mode, setMode] = useState<CostSource>("manual_estimate");
  const [selectedSupplierId, setSelectedSupplierId] = useState<string>("");
  
  const [rateCards, setRateCards] = useState<SupplierRateCard[]>([]);
  const [isLoadingRateCards, setIsLoadingRateCards] = useState(false);
  const [selectedRateCardId, setSelectedRateCardId] = useState<string>("");
  
  // Rate card auto-fill state
  const [rcCategory, setRcCategory] = useState("");
  const [rcItemName, setRcItemName] = useState("");
  const [rcUnit, setRcUnit] = useState("");
  const [rcBaseCost, setRcBaseCost] = useState(0);

  const fetchRateCards = async (supplierId: string) => {
    setIsLoadingRateCards(true);
    setRateCards([]);
    setSelectedRateCardId("");
    try {
      const res = await getActiveSupplierRateCardsForAllocation(supplierId);
      setRateCards(res.rateCards || []);
    } catch (err) {
      console.error("Failed to load rate cards", err);
    } finally {
      setIsLoadingRateCards(false);
    }
  };

  const handleModeChange = (newMode: CostSource) => {
    setMode(newMode);
    if (newMode === "rate_card" && selectedSupplierId) {
      fetchRateCards(selectedSupplierId);
    }
  };

  const handleSupplierChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const val = e.target.value;
    setSelectedSupplierId(val);
    if (mode === "rate_card" && val) {
      fetchRateCards(val);
    }
  };

  const handleRateCardChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const val = e.target.value;
    setSelectedRateCardId(val);
    const rc = rateCards.find(r => r.id === val);
    if (rc) {
      setRcCategory(rc.category || "");
      setRcItemName(rc.itemName);
      setRcUnit(rc.unit);
      setRcBaseCost(rc.baseCost);
    }
  };

  async function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    setError(null);
    setIsLoading(true);

    const formData = new FormData(e.currentTarget);
    const quantityStr = formData.get("quantity") as string;
    
    // estimated_total_cost is generated by the database and is never accepted from client input.
    let input: Record<string, unknown>;

    if (mode === "rate_card") {
      input = {
        serviceId,
        supplierId: selectedSupplierId,
        supplierRateCardId: selectedRateCardId,
        quantity: quantityStr ? parseFloat(quantityStr) : 0,
        costSource: "rate_card",
        scopeOfWork: (formData.get("scopeOfWork") as string) || undefined,
        internalNotes: (formData.get("internalNotes") as string) || undefined,
        // No client snapshot
      };
    } else {
      const estimatedUnitCostStr = formData.get("estimatedUnitCost") as string;
      input = {
        serviceId,
        supplierId: selectedSupplierId,
        category: formData.get("category") as string,
        itemName: formData.get("itemName") as string,
        unit: formData.get("unit") as string,
        quantity: quantityStr ? parseFloat(quantityStr) : 0,
        currency: "SAR",
        estimatedUnitCost: estimatedUnitCostStr ? parseFloat(estimatedUnitCostStr) : 0,
        costSource: "manual_estimate",
        scopeOfWork: (formData.get("scopeOfWork") as string) || undefined,
        internalNotes: (formData.get("internalNotes") as string) || undefined,
      };
    }

    const result = await createSupplierAllocation(input);

    if (result.success) {
      router.push(`/services/${serviceId}`);
      router.refresh();
    } else {
      setError(result.error || "Failed to create supplier allocation");
      setIsLoading(false);
    }
  }

  return (
    <form onSubmit={handleSubmit} className="bg-surface-container-lowest border border-outline-variant rounded-xl overflow-hidden">
      {canUseRateCards && (
        <div className="px-6 py-4 border-b border-outline-variant bg-surface-bright flex gap-4">
          <label className="flex items-center gap-2 cursor-pointer text-sm font-medium">
            <input 
              type="radio" 
              name="mode" 
              value="manual_estimate" 
              checked={mode === "manual_estimate"} 
              onChange={() => handleModeChange("manual_estimate")} 
              className="w-4 h-4 text-primary focus:ring-primary"
            />
            Manual Estimate
          </label>
          <label className="flex items-center gap-2 cursor-pointer text-sm font-medium">
            <input 
              type="radio" 
              name="mode" 
              value="rate_card" 
              checked={mode === "rate_card"} 
              onChange={() => handleModeChange("rate_card")} 
              className="w-4 h-4 text-primary focus:ring-primary"
            />
            From Rate Card
          </label>
        </div>
      )}

      <div className="p-6 grid grid-cols-1 md:grid-cols-2 gap-6">
        <div className="md:col-span-2 space-y-2">
          <label htmlFor="supplierId" className="block text-sm font-semibold text-on-surface">
            Supplier <span className="text-error">*</span>
          </label>
          <select
            id="supplierId"
            name="supplierId"
            required
            value={selectedSupplierId}
            onChange={handleSupplierChange}
            className="w-full px-4 py-2 bg-surface border border-outline-variant rounded-lg text-on-surface focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent transition-all"
            disabled={isLoading}
          >
            <option value="">Select a supplier...</option>
            {suppliers.map((s) => (
              <option key={s.id} value={s.id}>
                {s.name}
              </option>
            ))}
          </select>
        </div>

        {mode === "rate_card" && (
          <div className="md:col-span-2 space-y-2">
            <label htmlFor="supplierRateCardId" className="block text-sm font-semibold text-on-surface">
              Rate Card Item <span className="text-error">*</span>
            </label>
            <select
              id="supplierRateCardId"
              name="supplierRateCardId"
              required={mode === "rate_card"}
              value={selectedRateCardId}
              onChange={handleRateCardChange}
              className="w-full px-4 py-2 bg-surface border border-outline-variant rounded-lg text-on-surface focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent transition-all"
              disabled={isLoading || !selectedSupplierId || isLoadingRateCards}
            >
              <option value="">
                {isLoadingRateCards 
                  ? "Loading rate cards..." 
                  : !selectedSupplierId 
                    ? "Select a supplier first" 
                    : rateCards.length === 0 
                      ? "No active rate cards found" 
                      : "Select a rate card..."}
              </option>
              {rateCards.map((r) => (
                <option key={r.id} value={r.id}>
                  {r.itemName} ({r.category}) - {r.baseCost} SAR / {r.unit}
                </option>
              ))}
            </select>
          </div>
        )}

        <div className="space-y-2">
          <label htmlFor="category" className="block text-sm font-semibold text-on-surface">
            Category <span className="text-error">*</span>
          </label>
          <input
            type="text"
            id="category"
            name="category"
            required={mode === "manual_estimate"}
            value={mode === "rate_card" ? rcCategory : undefined}
            readOnly={mode === "rate_card"}
            className="w-full px-4 py-2 bg-surface border border-outline-variant rounded-lg text-on-surface focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent transition-all read-only:bg-surface-container-low read-only:text-on-surface-variant"
            placeholder="e.g. Venue, Catering, AV"
            disabled={isLoading}
          />
        </div>

        <div className="space-y-2">
          <label htmlFor="itemName" className="block text-sm font-semibold text-on-surface">
            Item Name <span className="text-error">*</span>
          </label>
          <input
            type="text"
            id="itemName"
            name="itemName"
            required={mode === "manual_estimate"}
            value={mode === "rate_card" ? rcItemName : undefined}
            readOnly={mode === "rate_card"}
            className="w-full px-4 py-2 bg-surface border border-outline-variant rounded-lg text-on-surface focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent transition-all read-only:bg-surface-container-low read-only:text-on-surface-variant"
            placeholder="e.g. Main Hall Rental"
            disabled={isLoading}
          />
        </div>

        <div className="space-y-2">
          <label htmlFor="unit" className="block text-sm font-semibold text-on-surface">
            Unit <span className="text-error">*</span>
          </label>
          <input
            type="text"
            id="unit"
            name="unit"
            required={mode === "manual_estimate"}
            value={mode === "rate_card" ? rcUnit : undefined}
            readOnly={mode === "rate_card"}
            className="w-full px-4 py-2 bg-surface border border-outline-variant rounded-lg text-on-surface focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent transition-all read-only:bg-surface-container-low read-only:text-on-surface-variant"
            placeholder="e.g. Days, Pax, Pieces"
            disabled={isLoading}
          />
        </div>

        <div className="space-y-2">
          <label htmlFor="quantity" className="block text-sm font-semibold text-on-surface">
            Quantity <span className="text-error">*</span>
          </label>
          <input
            type="number"
            id="quantity"
            name="quantity"
            min="0.01"
            step="0.01"
            required
            className="w-full px-4 py-2 bg-surface border border-outline-variant rounded-lg text-on-surface focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent transition-all"
            placeholder="1"
            disabled={isLoading}
          />
        </div>

        <div className="space-y-2">
          <label htmlFor="estimatedUnitCost" className="block text-sm font-semibold text-on-surface">
            {mode === "rate_card" ? "Rate Card Unit Cost (SAR)" : "Estimated Unit Cost (SAR)"} <span className="text-error">*</span>
          </label>
          <input
            type="number"
            id="estimatedUnitCost"
            name="estimatedUnitCost"
            min="0"
            step="0.01"
            required={mode === "manual_estimate"}
            value={mode === "rate_card" ? rcBaseCost : undefined}
            readOnly={mode === "rate_card"}
            className="w-full px-4 py-2 bg-surface border border-outline-variant rounded-lg text-on-surface focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent transition-all read-only:bg-surface-container-low read-only:text-on-surface-variant"
            placeholder="0.00"
            disabled={isLoading}
          />
        </div>

        <div className="md:col-span-2 space-y-2">
          <label htmlFor="scopeOfWork" className="block text-sm font-semibold text-on-surface">
            Scope of Work
          </label>
          <textarea
            id="scopeOfWork"
            name="scopeOfWork"
            rows={3}
            className="w-full px-4 py-2 bg-surface border border-outline-variant rounded-lg text-on-surface focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent transition-all resize-none"
            placeholder="Detailed description of what the supplier will provide..."
            disabled={isLoading}
          />
        </div>

        <div className="md:col-span-2 space-y-2">
          <label htmlFor="internalNotes" className="block text-sm font-semibold text-on-surface">
            Internal Notes
          </label>
          <textarea
            id="internalNotes"
            name="internalNotes"
            rows={2}
            className="w-full px-4 py-2 bg-surface border border-outline-variant rounded-lg text-on-surface focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent transition-all resize-none"
            placeholder="Internal notes for operations team..."
            disabled={isLoading}
          />
        </div>
      </div>

      {error && (
        <div className="px-6 py-4 bg-error-container text-on-error-container text-sm font-medium border-t border-error-container">
          {error}
        </div>
      )}

      <div className="px-6 py-4 bg-surface-bright border-t border-outline-variant flex items-center justify-end gap-3">
        <button
          type="button"
          onClick={() => router.push(`/services/${serviceId}`)}
          disabled={isLoading}
          className="px-4 py-2 font-semibold text-on-surface hover:bg-surface-container-low rounded-lg transition-colors disabled:opacity-50"
        >
          Cancel
        </button>
        <button
          type="submit"
          disabled={isLoading || (mode === "rate_card" && !selectedRateCardId)}
          className="px-6 py-2 bg-primary text-on-primary font-semibold rounded-lg hover:bg-primary-container transition-colors disabled:opacity-50 flex items-center justify-center min-w-[120px]"
        >
          {isLoading ? (
            <span className="w-5 h-5 border-2 border-on-primary border-t-transparent rounded-full animate-spin"></span>
          ) : (
            "Create Allocation"
          )}
        </button>
      </div>
    </form>
  );
}

