"use server";

import { revalidatePath } from "next/cache";
import { createAdminClient } from "@/lib/supabase/admin";
import { requirePermission, checkPermission } from "@/lib/auth/permissions";
import { UnauthorizedError, ForbiddenError } from "@/lib/auth/errors";
import { supplierAllocationCreateSchema, supplierAllocationCancelSchema, supplierAllocationUpdateSchema } from "./schemas";
import { mapSupplierAllocationRow } from "./mappers";
import type { SupplierAllocation } from "./types";

export type ActionResult<T = void> = {
  success: boolean;
  error?: string;
  data?: T;
};

function firstValidationError(parsed: { error: { issues: { message: string }[] } }) {
  return parsed.error.issues[0]?.message ?? "Validation failed";
}

async function checkActiveSupplierBooking(
  supabase: ReturnType<typeof createAdminClient>,
  allocationId: string
): Promise<{ active: boolean; error?: string }> {
  try {
    const { data, error } = await supabase
      .from("supplier_bookings")
      .select("id")
      .eq("source_allocation_id", allocationId)
      .eq("is_deleted", false)
      .neq("status", "cancelled")
      .limit(1)
      .maybeSingle();

    if (error) {
      console.error("[checkActiveSupplierBooking] Supabase error:", error.message);
      return { active: false, error: "Failed to verify booking status. Please try again." };
    }

    return { active: !!data };
  } catch (err) {
    console.error("[checkActiveSupplierBooking] Unexpected error:", err instanceof Error ? err.message : "Unknown");
    return { active: false, error: "An unexpected error occurred while verifying booking status." };
  }
}

export async function createSupplierAllocation(
  input: unknown
): Promise<ActionResult<SupplierAllocation>> {
  try {
    const user = await requirePermission("supplier_allocations:write");
    await requirePermission("supplier_allocations:read_cost");
    const parsed = supplierAllocationCreateSchema.safeParse(input);

    if (!parsed.success) {
      return { success: false, error: firstValidationError(parsed) };
    }



    const supabase = createAdminClient();

    // Cross-table check 1: Service check
    const { data: service, error: serviceError } = await supabase
      .from("services")
      .select("status")
      .eq("id", parsed.data.serviceId)
      .is("deleted_at", null)
      .single();

    if (serviceError || !service || service.status === "Cancelled" || service.status === "Completed") {
      return { success: false, error: "Service is unavailable for supplier allocation." };
    }

    // Cross-table check 2: Supplier check
    const { data: supplier, error: supplierError } = await supabase
      .from("suppliers")
      .select("status")
      .eq("id", parsed.data.supplierId)
      .eq("is_deleted", false)
      .single();

    if (supplierError || !supplier || supplier.status !== "active") {
      return { success: false, error: "Supplier is unavailable for allocation." };
    }

    // Cross-table check 3: Approved quotation check
    if (parsed.data.approvedQuotationId) {
      const { data: quotation, error: quotationError } = await supabase
        .from("quotations")
        .select("status, service_id")
        .eq("id", parsed.data.approvedQuotationId)
        .eq("is_deleted", false)
        .single();

      if (
        quotationError ||
        !quotation ||
        quotation.status !== "approved" ||
        quotation.service_id !== parsed.data.serviceId
      ) {
        return { success: false, error: "Approved quotation is invalid for this service." };
      }
    }

    // Server-side snapshot logic for rate_card mode.
    // estimated_total_cost is generated by the database and is never accepted from client input.
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    let insertPayload: any;

    if (parsed.data.costSource === "rate_card") {
      if (!parsed.data.supplierRateCardId) {
        return { success: false, error: "Rate card ID is required." };
      }

      const { data: rateCard, error: rcError } = await supabase
        .from("supplier_rate_cards")
        .select("*")
        .eq("id", parsed.data.supplierRateCardId)
        .single();

      if (rcError || !rateCard) {
        return { success: false, error: "Rate card not found." };
      }

      if (rateCard.is_deleted || rateCard.status !== "active") {
        return { success: false, error: "Rate card is not active or deleted." };
      }

      if (rateCard.supplier_id !== parsed.data.supplierId) {
        return { success: false, error: "Rate card does not belong to the selected supplier." };
      }

      if (rateCard.currency !== "SAR" || rateCard.base_cost == null || rateCard.base_cost < 0) {
        return { success: false, error: "Invalid rate card cost or currency." };
      }

      const today = new Date().toISOString().split("T")[0];
      if (rateCard.valid_to && rateCard.valid_to < today) {
        return { success: false, error: "Rate card is expired." };
      }

      const rateCardSnapshot = {
        rateCardId: rateCard.id,
        supplierId: rateCard.supplier_id,
        itemName: rateCard.item_name,
        unit: rateCard.unit,
        currency: rateCard.currency,
        baseCost: rateCard.base_cost,
        validFrom: rateCard.valid_from,
        validTo: rateCard.valid_to,
      };

      insertPayload = {
        service_id: parsed.data.serviceId,
        supplier_id: parsed.data.supplierId,
        supplier_rate_card_id: rateCard.id,
        approved_quotation_id: parsed.data.approvedQuotationId ?? null,
        status: "draft",
        category: rateCard.category,
        item_name: rateCard.item_name,
        unit: rateCard.unit,
        quantity: parsed.data.quantity,
        currency: "SAR",
        estimated_unit_cost: rateCard.base_cost,
        cost_source: "rate_card",
        rate_card_snapshot: rateCardSnapshot,
        scope_of_work: parsed.data.scopeOfWork ?? null,
        internal_notes: parsed.data.internalNotes ?? null,
        created_by: user.clerk_user_id,
        updated_by: user.clerk_user_id,
      };
    } else {
      insertPayload = {
        service_id: parsed.data.serviceId,
        supplier_id: parsed.data.supplierId,
        approved_quotation_id: parsed.data.approvedQuotationId ?? null,
        status: "draft",
        category: parsed.data.category,
        item_name: parsed.data.itemName,
        unit: parsed.data.unit,
        quantity: parsed.data.quantity,
        currency: "SAR",
        estimated_unit_cost: parsed.data.estimatedUnitCost,
        cost_source: "manual_estimate",
        scope_of_work: parsed.data.scopeOfWork ?? null,
        internal_notes: parsed.data.internalNotes ?? null,
        created_by: user.clerk_user_id,
        updated_by: user.clerk_user_id,
      };
    }

    const { data: createdRow, error } = await supabase
      .from("service_supplier_allocations")
      .insert(insertPayload)
      .select()
      .single();

    if (error) {
      console.error("[createSupplierAllocation] Supabase error:", error.message);
      return { success: false, error: "Failed to create supplier allocation. Please try again." };
    }

    const canReadCost = await checkPermission("supplier_allocations:read_cost");
    const mappedData = mapSupplierAllocationRow(createdRow, { canReadCost });

    revalidatePath("/services");
    revalidatePath(`/services/${parsed.data.serviceId}`);

    return { success: true, data: mappedData };
  } catch (err) {
    if (err instanceof UnauthorizedError) return { success: false, error: "Unauthorized" };
    if (err instanceof ForbiddenError) return { success: false, error: "Forbidden" };
    console.error("[createSupplierAllocation] Unexpected error:", err instanceof Error ? err.message : "Unknown");
    return { success: false, error: "An unexpected error occurred." };
  }
}

export async function cancelSupplierAllocation(
  id: string,
  input: unknown
): Promise<ActionResult<SupplierAllocation>> {
  try {
    const user = await requirePermission("supplier_allocations:cancel");

    if (!id || typeof id !== "string" || id.trim() === "") {
      return { success: false, error: "Supplier allocation id is required." };
    }

    const parsed = supplierAllocationCancelSchema.safeParse(input);
    if (!parsed.success) {
      return { success: false, error: firstValidationError(parsed) };
    }

    const supabase = createAdminClient();

    const { data: existingAllocation, error: fetchError } = await supabase
      .from("service_supplier_allocations")
      .select("*")
      .eq("id", id)
      .eq("is_deleted", false)
      .single();

    if (fetchError || !existingAllocation) {
      return { success: false, error: "Supplier allocation not found." };
    }

    if (existingAllocation.status === "cancelled") {
      return { success: false, error: "Supplier allocation is already cancelled." };
    }

    const bookingCheck = await checkActiveSupplierBooking(supabase, id);
    if (bookingCheck.error) {
      return { success: false, error: bookingCheck.error };
    }
    if (bookingCheck.active) {
      return { success: false, error: "This allocation cannot be modified because it is linked to an active supplier booking." };
    }

    // Cross-table check 1: Service check
    const { data: service, error: serviceError } = await supabase
      .from("services")
      .select("status")
      .eq("id", existingAllocation.service_id)
      .is("deleted_at", null)
      .single();

    if (serviceError || !service || service.status === "Cancelled" || service.status === "Completed") {
      return { success: false, error: "Service is unavailable for supplier allocation cancel." };
    }

    // Business cancellation preserves the row for audit/history and must not set is_deleted.
    const updatePayload = {
      status: "cancelled",
      cancelled_reason: parsed.data.cancelledReason,
      cancelled_at: new Date().toISOString(),
      cancelled_by: user.clerk_user_id,
      updated_by: user.clerk_user_id,
    };

    const { data: updatedRow, error: updateError } = await supabase
      .from("service_supplier_allocations")
      .update(updatePayload)
      .eq("id", id)
      .select()
      .single();

    if (updateError) {
      console.error("[cancelSupplierAllocation] Supabase error:", updateError.message);
      return { success: false, error: "Failed to cancel supplier allocation. Please try again." };
    }

    const canReadCost = await checkPermission("supplier_allocations:read_cost");
    const mappedData = mapSupplierAllocationRow(updatedRow, { canReadCost });

    revalidatePath("/services");
    revalidatePath(`/services/${existingAllocation.service_id}`);

    return { success: true, data: mappedData };
  } catch (err) {
    if (err instanceof UnauthorizedError) return { success: false, error: "Unauthorized" };
    if (err instanceof ForbiddenError) return { success: false, error: "Forbidden" };
    console.error("[cancelSupplierAllocation] Unexpected error:", err instanceof Error ? err.message : "Unknown");
    return { success: false, error: "An unexpected error occurred." };
  }
}

export async function updateSupplierAllocation(
  id: string,
  input: unknown
): Promise<ActionResult<SupplierAllocation>> {
  try {
    const user = await requirePermission("supplier_allocations:write");
    await requirePermission("supplier_allocations:read_cost");

    if (!id || typeof id !== "string" || id.trim() === "") {
      return { success: false, error: "Supplier allocation id is required." };
    }

    const trimmedId = id.trim();

    const parsed = supplierAllocationUpdateSchema.safeParse(input);
    if (!parsed.success) {
      return { success: false, error: firstValidationError(parsed) };
    }

    if (parsed.data.costSource === "rate_card") {
      return { success: false, error: "Rate-card allocations cannot be manually updated yet." };
    }

    const supabase = createAdminClient();

    const { data: existingAllocation, error: fetchError } = await supabase
      .from("service_supplier_allocations")
      .select("*")
      .eq("id", trimmedId)
      .eq("is_deleted", false)
      .single();

    if (fetchError || !existingAllocation) {
      return { success: false, error: "Supplier allocation not found." };
    }

    if (existingAllocation.status === "cancelled") {
      return { success: false, error: "Cannot update a cancelled supplier allocation." };
    }

    if (existingAllocation.cost_source === "rate_card") {
      return { success: false, error: "Rate-card allocations cannot be manually updated yet." };
    }

    const bookingCheck = await checkActiveSupplierBooking(supabase, trimmedId);
    if (bookingCheck.error) {
      return { success: false, error: bookingCheck.error };
    }
    if (bookingCheck.active) {
      return { success: false, error: "This allocation cannot be modified because it is linked to an active supplier booking." };
    }

    const nextStatus = parsed.data.status ?? existingAllocation.status;

    const allowedStatusTransitions: Record<string, string[]> = {
      draft: ["draft", "planned"],
      planned: ["planned", "selected"],
      selected: ["selected"],
      cancelled: [],
    };

    if (!allowedStatusTransitions[existingAllocation.status]?.includes(nextStatus)) {
      return {
        success: false,
        error: "Invalid supplier allocation status transition.",
      };
    }

    // Cross-table check 1: Service check
    const { data: service, error: serviceError } = await supabase
      .from("services")
      .select("status")
      .eq("id", existingAllocation.service_id)
      .is("deleted_at", null)
      .single();

    if (serviceError || !service || service.status === "Cancelled" || service.status === "Completed") {
      return { success: false, error: "Service is unavailable for supplier allocation update." };
    }

    // Cross-table check 2: Supplier check (immutable, but check active status)
    const { data: supplier, error: supplierError } = await supabase
      .from("suppliers")
      .select("status")
      .eq("id", existingAllocation.supplier_id)
      .eq("is_deleted", false)
      .single();

    if (supplierError || !supplier || supplier.status !== "active") {
      return { success: false, error: "Supplier is unavailable for allocation update." };
    }

    // Cross-table check 3: Approved quotation check
    if (parsed.data.approvedQuotationId) {
      const { data: quotation, error: quotationError } = await supabase
        .from("quotations")
        .select("status, service_id")
        .eq("id", parsed.data.approvedQuotationId)
        .eq("is_deleted", false)
        .single();

      if (
        quotationError ||
        !quotation ||
        quotation.status !== "approved" ||
        quotation.service_id !== existingAllocation.service_id
      ) {
        return { success: false, error: "Approved quotation is invalid for this service." };
      }
    }

    const updatePayload = {
      status: nextStatus,
      category: parsed.data.category,
      item_name: parsed.data.itemName,
      unit: parsed.data.unit,
      quantity: parsed.data.quantity,
      currency: "SAR",
      estimated_unit_cost: parsed.data.estimatedUnitCost,
      cost_source: "manual_estimate",
      scope_of_work: parsed.data.scopeOfWork ?? null,
      internal_notes: parsed.data.internalNotes ?? null,
      approved_quotation_id: parsed.data.approvedQuotationId ?? existingAllocation.approved_quotation_id,
      updated_by: user.clerk_user_id,
    };

    const { data: updatedRow, error: updateError } = await supabase
      .from("service_supplier_allocations")
      .update(updatePayload)
      .eq("id", trimmedId)
      .select()
      .single();

    if (updateError) {
      console.error("[updateSupplierAllocation] Supabase error:", updateError.message);
      return { success: false, error: "Failed to update supplier allocation. Please try again." };
    }

    const canReadCost = await checkPermission("supplier_allocations:read_cost");
    const mappedData = mapSupplierAllocationRow(updatedRow, { canReadCost });

    revalidatePath("/services");
    revalidatePath(`/services/${existingAllocation.service_id}`);

    return { success: true, data: mappedData };
  } catch (err) {
    if (err instanceof UnauthorizedError) return { success: false, error: "Unauthorized" };
    if (err instanceof ForbiddenError) return { success: false, error: "Forbidden" };
    console.error("[updateSupplierAllocation] Unexpected error:", err instanceof Error ? err.message : "Unknown");
    return { success: false, error: "An unexpected error occurred." };
  }
}

export async function deleteSupplierAllocation(id: string): Promise<ActionResult<SupplierAllocation>> {
  try {
    const user = await requirePermission("supplier_allocations:write");

    if (!id || typeof id !== "string" || id.trim() === "") {
      return { success: false, error: "Supplier allocation id is required." };
    }

    const trimmedId = id.trim();
    const supabase = createAdminClient();

    const { data: existingAllocation, error: fetchError } = await supabase
      .from("service_supplier_allocations")
      .select("*")
      .eq("id", trimmedId)
      .single();

    if (fetchError || !existingAllocation) {
      return { success: false, error: "Supplier allocation not found." };
    }

    if (existingAllocation.is_deleted) {
      return { success: false, error: "Supplier allocation is already deleted." };
    }

    const bookingCheck = await checkActiveSupplierBooking(supabase, trimmedId);
    if (bookingCheck.error) {
      return { success: false, error: bookingCheck.error };
    }
    if (bookingCheck.active) {
      return { success: false, error: "This allocation cannot be modified because it is linked to an active supplier booking." };
    }

    // Cross-table check 1: Service check
    const { data: service, error: serviceError } = await supabase
      .from("services")
      .select("status")
      .eq("id", existingAllocation.service_id)
      .is("deleted_at", null)
      .single();

    if (serviceError || !service || service.status === "Cancelled" || service.status === "Completed") {
      return { success: false, error: "Service is unavailable for supplier allocation deletion." };
    }

    const updatePayload = {
      is_deleted: true,
      updated_by: user.clerk_user_id,
      updated_at: new Date().toISOString(),
    };

    const { data: updatedRow, error: updateError } = await supabase
      .from("service_supplier_allocations")
      .update(updatePayload)
      .eq("id", trimmedId)
      .select()
      .single();

    if (updateError) {
      console.error("[deleteSupplierAllocation] Supabase error:", updateError.message);
      return { success: false, error: "Failed to delete supplier allocation. Please try again." };
    }

    const canReadCost = await checkPermission("supplier_allocations:read_cost");
    const mappedData = mapSupplierAllocationRow(updatedRow, { canReadCost });

    revalidatePath("/services");
    revalidatePath(`/services/${existingAllocation.service_id}`);

    return { success: true, data: mappedData };
  } catch (err) {
    if (err instanceof UnauthorizedError) return { success: false, error: "Unauthorized" };
    if (err instanceof ForbiddenError) return { success: false, error: "Forbidden" };
    console.error("[deleteSupplierAllocation] Unexpected error:", err instanceof Error ? err.message : "Unknown");
    return { success: false, error: "An unexpected error occurred." };
  }
}

export async function restoreSupplierAllocation(id: string): Promise<ActionResult<SupplierAllocation>> {
  try {
    const user = await requirePermission("supplier_allocations:write");

    if (!id || typeof id !== "string" || id.trim() === "") {
      return { success: false, error: "Supplier allocation id is required." };
    }

    const trimmedId = id.trim();
    const supabase = createAdminClient();

    const { data: existingAllocation, error: fetchError } = await supabase
      .from("service_supplier_allocations")
      .select("*")
      .eq("id", trimmedId)
      .single();

    if (fetchError || !existingAllocation) {
      return { success: false, error: "Supplier allocation not found." };
    }

    if (!existingAllocation.is_deleted) {
      return { success: false, error: "Supplier allocation is not deleted." };
    }

    const bookingCheck = await checkActiveSupplierBooking(supabase, trimmedId);
    if (bookingCheck.error) {
      return { success: false, error: bookingCheck.error };
    }
    if (bookingCheck.active) {
      return { success: false, error: "This allocation cannot be modified because it is linked to an active supplier booking." };
    }

    // Cross-table check 1: Service check
    const { data: service, error: serviceError } = await supabase
      .from("services")
      .select("status")
      .eq("id", existingAllocation.service_id)
      .is("deleted_at", null)
      .single();

    if (serviceError || !service || service.status === "Cancelled" || service.status === "Completed") {
      return { success: false, error: "Service is unavailable for supplier allocation restoration." };
    }

    const updatePayload = {
      is_deleted: false,
      updated_by: user.clerk_user_id,
      updated_at: new Date().toISOString(),
    };

    const { data: updatedRow, error: updateError } = await supabase
      .from("service_supplier_allocations")
      .update(updatePayload)
      .eq("id", trimmedId)
      .select()
      .single();

    if (updateError) {
      console.error("[restoreSupplierAllocation] Supabase error:", updateError.message);
      return { success: false, error: "Failed to restore supplier allocation. Please try again." };
    }

    const canReadCost = await checkPermission("supplier_allocations:read_cost");
    const mappedData = mapSupplierAllocationRow(updatedRow, { canReadCost });

    revalidatePath("/services");
    revalidatePath(`/services/${existingAllocation.service_id}`);

    return { success: true, data: mappedData };
  } catch (err) {
    if (err instanceof UnauthorizedError) return { success: false, error: "Unauthorized" };
    if (err instanceof ForbiddenError) return { success: false, error: "Forbidden" };
    console.error("[restoreSupplierAllocation] Unexpected error:", err instanceof Error ? err.message : "Unknown");
    return { success: false, error: "An unexpected error occurred." };
  }
}
