"use server";

import { revalidatePath } from "next/cache";
import { createAdminClient } from "@/lib/supabase/admin";
import { requirePermission, checkPermission } from "@/lib/auth/permissions";
import { UnauthorizedError, ForbiddenError } from "@/lib/auth/errors";
import { supplierAllocationCreateSchema } from "./schemas";
import { mapSupplierAllocationRow } from "./mappers";
import type { SupplierAllocation } from "./types";

export type ActionResult<T = void> = {
  success: boolean;
  error?: string;
  data?: T;
};

function firstValidationError(parsed: { error: { issues: { message: string }[] } }) {
  return parsed.error.issues[0]?.message ?? "Validation failed";
}

export async function createSupplierAllocation(
  input: unknown
): Promise<ActionResult<SupplierAllocation>> {
  try {
    const user = await requirePermission("supplier_allocations:write");
    const parsed = supplierAllocationCreateSchema.safeParse(input);

    if (!parsed.success) {
      return { success: false, error: firstValidationError(parsed) };
    }

    if (parsed.data.costSource === "rate_card") {
      return { success: false, error: "Rate card allocations are not yet supported." };
    }

    const supabase = createAdminClient();

    // Cross-table check 1: Service check
    const { data: service, error: serviceError } = await supabase
      .from("services")
      .select("status")
      .eq("id", parsed.data.serviceId)
      .is("deleted_at", null)
      .single();

    if (serviceError || !service || service.status === "Cancelled" || service.status === "Completed") {
      return { success: false, error: "Service is unavailable for supplier allocation." };
    }

    // Cross-table check 2: Supplier check
    const { data: supplier, error: supplierError } = await supabase
      .from("suppliers")
      .select("status")
      .eq("id", parsed.data.supplierId)
      .eq("is_deleted", false)
      .single();

    if (supplierError || !supplier || supplier.status !== "active") {
      return { success: false, error: "Supplier is unavailable for allocation." };
    }

    // Cross-table check 3: Approved quotation check
    if (parsed.data.approvedQuotationId) {
      const { data: quotation, error: quotationError } = await supabase
        .from("quotations")
        .select("status, service_id")
        .eq("id", parsed.data.approvedQuotationId)
        .eq("is_deleted", false)
        .single();

      if (
        quotationError ||
        !quotation ||
        quotation.status !== "approved" ||
        quotation.service_id !== parsed.data.serviceId
      ) {
        return { success: false, error: "Approved quotation is invalid for this service." };
      }
    }

    // Manual allocation creation is server-only.
    // Rate-card allocations are deferred because snapshots must be generated server-side.
    // estimated_total_cost is generated by the database and is never accepted from client input.
    const insertPayload = {
      service_id: parsed.data.serviceId,
      supplier_id: parsed.data.supplierId,
      approved_quotation_id: parsed.data.approvedQuotationId ?? null,
      status: "draft",
      category: parsed.data.category,
      item_name: parsed.data.itemName,
      unit: parsed.data.unit,
      quantity: parsed.data.quantity,
      currency: "SAR",
      estimated_unit_cost: parsed.data.estimatedUnitCost,
      cost_source: "manual_estimate",
      scope_of_work: parsed.data.scopeOfWork ?? null,
      internal_notes: parsed.data.internalNotes ?? null,
      created_by: user.clerk_user_id,
      updated_by: user.clerk_user_id,
    };

    const { data: createdRow, error } = await supabase
      .from("service_supplier_allocations")
      .insert(insertPayload)
      .select()
      .single();

    if (error) {
      console.error("[createSupplierAllocation] Supabase error:", error.message);
      return { success: false, error: "Failed to create supplier allocation. Please try again." };
    }

    const canReadCost = await checkPermission("supplier_allocations:read_cost");
    const mappedData = mapSupplierAllocationRow(createdRow, { canReadCost });

    revalidatePath("/services");
    revalidatePath(`/services/${parsed.data.serviceId}`);

    return { success: true, data: mappedData };
  } catch (err) {
    if (err instanceof UnauthorizedError) return { success: false, error: "Unauthorized" };
    if (err instanceof ForbiddenError) return { success: false, error: "Forbidden" };
    console.error("[createSupplierAllocation] Unexpected error:", err instanceof Error ? err.message : "Unknown");
    return { success: false, error: "An unexpected error occurred." };
  }
}
