import type {
  SupplierAllocationRow,
  SupplierAllocation,
  SupplierAllocationMapperOptions,
} from "./types";

/**
 * Supplier allocation costs are internal only.
 * Use canReadCost=false unless supplier_allocations:read_cost has been checked by the caller.
 * Customer-facing routes/PDFs must not import allocation cost mappers.
 * estimatedTotalCost is generated by the database and must never be accepted from client input.
 */

export function mapSupplierAllocationRow(
  row: SupplierAllocationRow,
  options: SupplierAllocationMapperOptions
): SupplierAllocation {
  const { canReadCost } = options;

  let computedSupplierName: string | null = null;
  if (row.supplier) {
    computedSupplierName =
      row.supplier.display_name ||
      row.supplier.name ||
      row.supplier.legal_name ||
      row.supplier.contact ||
      row.supplier_id;
  }

  return {
    id: row.id,
    serviceId: row.service_id,
    supplierId: row.supplier_id,
    supplierRateCardId: row.supplier_rate_card_id,
    approvedQuotationId: row.approved_quotation_id,
    status: row.status,
    category: row.category,
    itemName: row.item_name,
    unit: row.unit,
    quantity: Number(row.quantity),
    currency: row.currency,
    // Redact costs if user lacks permission
    estimatedUnitCost: canReadCost ? Number(row.estimated_unit_cost) : null,
    estimatedTotalCost: canReadCost ? Number(row.estimated_total_cost) : null,
    costSource: row.cost_source,
    // Redact snapshot if user lacks permission
    rateCardSnapshot: canReadCost ? row.rate_card_snapshot : null,
    scopeOfWork: row.scope_of_work,
    internalNotes: row.internal_notes,
    createdBy: row.created_by,
    updatedBy: row.updated_by,
    cancelledAt: row.cancelled_at,
    cancelledBy: row.cancelled_by,
    cancelledReason: row.cancelled_reason,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
    isDeleted: row.is_deleted,
    supplierName: computedSupplierName,
  };
}

export function mapSupplierAllocationRows(
  rows: SupplierAllocationRow[],
  options: SupplierAllocationMapperOptions
): SupplierAllocation[] {
  return rows.map((row) => mapSupplierAllocationRow(row, options));
}
