import assert from "node:assert/strict";
import test from "node:test";
import { getCustomersDictionary } from "../i18n/dictionaries/customers.ts";
import { formatUiNumber } from "../i18n/formatting.ts";
import {
  DEFAULT_EXCEL_EXPORT_CHROME_EN,
  buildExcelExportFiltersLine,
  buildExcelExportMetaLine,
  formatExcelExportDateTime,
} from "./exportExcel.ts";

const ARABIC_INDIC = /[٠-٩]/;

test("1. English export chrome defaults match pre-i18n workbook labels", () => {
  assert.equal(DEFAULT_EXCEL_EXPORT_CHROME_EN.filteredView, "Filtered View");
  assert.equal(DEFAULT_EXCEL_EXPORT_CHROME_EN.generatedAtLabel, "Generated At");
  assert.equal(DEFAULT_EXCEL_EXPORT_CHROME_EN.generatedByLabel, "Generated By");
  assert.equal(DEFAULT_EXCEL_EXPORT_CHROME_EN.totalRecordsLabel, "Total Records");
  assert.equal(DEFAULT_EXCEL_EXPORT_CHROME_EN.filtersLabel, "Filters");
  assert.equal(DEFAULT_EXCEL_EXPORT_CHROME_EN.allRecords, "All records");
  assert.equal(DEFAULT_EXCEL_EXPORT_CHROME_EN.systemGenerated, "System Generated");
  assert.equal(DEFAULT_EXCEL_EXPORT_CHROME_EN.defaultSheetName, "Report");
});

test("2. English meta/filters lines preserve near-equivalent structure", () => {
  const en = getCustomersDictionary("en").list.report.chrome;
  const date = new Date("2026-07-12T12:00:00.000Z");
  const formattedDate = formatExcelExportDateTime("en", date);
  const meta = buildExcelExportMetaLine({
    chrome: en,
    formattedDate,
    generatedBy: en.systemGenerated,
    totalRecordsDisplay: formatUiNumber("en", 12),
  });
  assert.match(meta, /Filtered View/);
  assert.match(meta, /Generated At:/);
  assert.match(meta, /Generated By: System Generated/);
  assert.match(meta, /Total Records: 12/);
  assert.doesNotMatch(meta, ARABIC_INDIC);

  const filtersEmpty = buildExcelExportFiltersLine({ chrome: en, filters: [] });
  assert.equal(filtersEmpty, "Filters: All records");

  const filtersActive = buildExcelExportFiltersLine({
    chrome: en,
    filters: ["Status: Active", "City: Riyadh"],
  });
  assert.equal(filtersActive, "Filters: Status: Active, City: Riyadh");
});

test("3. Arabic meta/filters lines use approved chrome and Western digits", () => {
  const ar = getCustomersDictionary("ar").list.report.chrome;
  const date = new Date("2026-07-12T12:00:00.000Z");
  const formattedDate = formatExcelExportDateTime("ar", date);
  const total = formatUiNumber("ar", 1500, { useGrouping: true });

  assert.equal(ar.filteredView, "عرض مُصفّى");
  assert.equal(ar.defaultSheetName, "تقرير");
  assert.equal(ar.systemGenerated, "تم إنشاؤه بواسطة النظام");
  assert.doesNotMatch(formattedDate, ARABIC_INDIC);
  assert.match(formattedDate, /\d/);

  const meta = buildExcelExportMetaLine({
    chrome: ar,
    formattedDate,
    generatedBy: ar.systemGenerated,
    totalRecordsDisplay: total,
  });
  assert.match(meta, /عرض مُصفّى/);
  assert.match(meta, /تاريخ الإنشاء:/);
  assert.match(meta, /تم الإنشاء بواسطة: تم إنشاؤه بواسطة النظام/);
  assert.match(meta, /إجمالي السجلات:/);
  assert.doesNotMatch(meta, ARABIC_INDIC);
  assert.match(total, /1[,.]?500|1500/);

  const filtersEmpty = buildExcelExportFiltersLine({ chrome: ar });
  assert.equal(filtersEmpty, "عوامل التصفية: كل السجلات");
});

test("4. Customers dictionary chrome aligns EN/AR keys; columns remain locale-specific", () => {
  const en = getCustomersDictionary("en").list.report;
  const ar = getCustomersDictionary("ar").list.report;
  assert.deepEqual(Object.keys(en.chrome).sort(), Object.keys(ar.chrome).sort());
  assert.equal(en.columns.customerNumber, "Customer Number");
  assert.equal(ar.columns.customerNumber, "رقم العميل");
  assert.equal(en.title, "Customers Report");
  assert.equal(ar.title, "تقرير العملاء");
});
