import ExcelJS from "exceljs";
import type { Locale } from "../i18n/locales.ts";
import { formatUiNumber, withLatnNumberingSystem } from "../i18n/formatting.ts";

export type ExcelColumn<T> = {
  header: string;
  key: keyof T | string;
  width?: number;
  value?: (row: T) => string | number | null | undefined;
  format?: "text" | "number" | "currency" | "date";
};

/**
 * Localizable workbook chrome (meta/filter rows + defaults).
 * Callers pass locale-specific copy; English defaults preserve prior chrome.
 */
export type ExcelExportChromeCopy = {
  filteredView: string;
  generatedAtLabel: string;
  generatedByLabel: string;
  totalRecordsLabel: string;
  filtersLabel: string;
  allRecords: string;
  systemGenerated: string;
  defaultSheetName: string;
};

export type ExcelReportMetadata = {
  companyName: string;
  brandName: string;
  reportTitle: string;
  generatedAt: Date;
  generatedBy?: string;
  filters?: string[];
  totalRecords: number;
  sheetName?: string;
  fileName: string;
};

/** English chrome matching the pre-i18n workbook strings (helper default). */
export const DEFAULT_EXCEL_EXPORT_CHROME_EN: ExcelExportChromeCopy = {
  filteredView: "Filtered View",
  generatedAtLabel: "Generated At",
  generatedByLabel: "Generated By",
  totalRecordsLabel: "Total Records",
  filtersLabel: "Filters",
  allRecords: "All records",
  systemGenerated: "System Generated",
  defaultSheetName: "Report",
};

const EXCEL_DATE_INTL_LOCALE: Record<Locale, string> = {
  en: "en-GB",
  ar: "ar-SA",
};

/**
 * Export timestamp: Asia/Riyadh, 24h, Western digits.
 * English stays near-equivalent to historical `en-GB` DD/MM/YYYY HH:mm.
 */
export function formatExcelExportDateTime(locale: Locale, date: Date): string {
  const formatted = new Intl.DateTimeFormat(
    EXCEL_DATE_INTL_LOCALE[locale],
    withLatnNumberingSystem({
      timeZone: "Asia/Riyadh",
      year: "numeric",
      month: "2-digit",
      day: "2-digit",
      hour: "2-digit",
      minute: "2-digit",
      hour12: false,
    }),
  ).format(date);

  return formatted.replace(", ", " ").replace(/\u200e|\u200f/g, "").trim();
}

export function buildExcelExportMetaLine(options: {
  chrome: ExcelExportChromeCopy;
  formattedDate: string;
  generatedBy: string;
  totalRecordsDisplay: string;
}): string {
  const { chrome, formattedDate, generatedBy, totalRecordsDisplay } = options;
  return [
    chrome.filteredView,
    `${chrome.generatedAtLabel}: ${formattedDate}`,
    `${chrome.generatedByLabel}: ${generatedBy}`,
    `${chrome.totalRecordsLabel}: ${totalRecordsDisplay}`,
  ].join(" | ");
}

export function buildExcelExportFiltersLine(options: {
  chrome: ExcelExportChromeCopy;
  filters?: string[];
}): string {
  const { chrome, filters } = options;
  const filtersText =
    filters && filters.length > 0 ? filters.join(", ") : chrome.allRecords;
  return `${chrome.filtersLabel}: ${filtersText}`;
}

export async function generateExcelReport<T>(options: {
  metadata: ExcelReportMetadata;
  columns: ExcelColumn<T>[];
  rows: T[];
  /** Session locale for date/number chrome. Defaults to English for helper compatibility. */
  locale?: Locale;
  /** Localizable chrome labels. Defaults to English strings matching prior output. */
  chrome?: ExcelExportChromeCopy;
}): Promise<void> {
  const { metadata, columns, rows } = options;
  const locale: Locale = options.locale ?? "en";
  const chrome = options.chrome ?? DEFAULT_EXCEL_EXPORT_CHROME_EN;
  const generatedBy =
    metadata.generatedBy?.trim() || chrome.systemGenerated;

  const workbook = new ExcelJS.Workbook();
  workbook.creator = metadata.brandName;
  workbook.lastModifiedBy = generatedBy;
  workbook.created = metadata.generatedAt;
  workbook.modified = metadata.generatedAt;

  const sheet = workbook.addWorksheet(
    metadata.sheetName || chrome.defaultSheetName,
    {
      views: [{ state: "frozen", xSplit: 0, ySplit: 5 }],
    },
  );

  const lastCol = columns.length;
  const formattedDate = formatExcelExportDateTime(locale, metadata.generatedAt);
  const totalRecordsDisplay = formatUiNumber(locale, metadata.totalRecords, {
    useGrouping: true,
  });

  // Shared navy fill for the header band
  const headerFill: ExcelJS.Fill = {
    type: "pattern",
    pattern: "solid",
    fgColor: { argb: "FF0f172a" }, // Deep navy blue (Tailwind slate-900)
  };

  // Row 1: Brand
  sheet.mergeCells(1, 1, 1, lastCol);
  const row1 = sheet.getCell(1, 1);
  row1.value = `${metadata.companyName} - ${metadata.brandName}`;
  row1.font = { size: 14, bold: true, color: { argb: "FFFFFFFF" } };
  row1.fill = headerFill;
  row1.alignment = { horizontal: "center", vertical: "middle" };
  sheet.getRow(1).height = 25;

  // Row 2: Report Title
  sheet.mergeCells(2, 1, 2, lastCol);
  const row2 = sheet.getCell(2, 1);
  row2.value = metadata.reportTitle;
  row2.font = { size: 16, bold: true, color: { argb: "FFFFFFFF" } };
  row2.fill = headerFill;
  row2.alignment = { horizontal: "center", vertical: "middle" };
  sheet.getRow(2).height = 30;

  // Row 3: Meta Info
  sheet.mergeCells(3, 1, 3, lastCol);
  const row3 = sheet.getCell(3, 1);
  row3.value = buildExcelExportMetaLine({
    chrome,
    formattedDate,
    generatedBy,
    totalRecordsDisplay,
  });
  row3.font = { size: 10, color: { argb: "FFCCCCCC" } }; // slightly muted white
  row3.fill = headerFill;
  row3.alignment = { horizontal: "center", vertical: "middle" };
  sheet.getRow(3).height = 20;

  // Row 4: Filters
  sheet.mergeCells(4, 1, 4, lastCol);
  const row4 = sheet.getCell(4, 1);
  row4.value = buildExcelExportFiltersLine({
    chrome,
    filters: metadata.filters,
  });
  row4.font = { size: 10, italic: true, color: { argb: "FFCCCCCC" } };
  row4.fill = headerFill;
  row4.alignment = { horizontal: "center", vertical: "middle" };
  sheet.getRow(4).height = 20;

  // 5. Table Headers (Row 5)
  const headerRowIndex = 5;
  const headerRow = sheet.getRow(headerRowIndex);

  columns.forEach((col, index) => {
    const colNumber = index + 1;
    const cell = headerRow.getCell(colNumber);
    cell.value = col.header;
    cell.font = { bold: true, color: { argb: "FFFFFFFF" } };
    cell.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "FF1e293b" }, // slightly lighter navy for column headers
    };
    cell.border = {
      top: { style: "thin", color: { argb: "FF334155" } },
      left: { style: "thin", color: { argb: "FF334155" } },
      bottom: { style: "thin", color: { argb: "FF334155" } },
      right: { style: "thin", color: { argb: "FF334155" } },
    };

    sheet.getColumn(colNumber).width = col.width || 20;
  });

  sheet.autoFilter = {
    from: { row: headerRowIndex, column: 1 },
    to: { row: headerRowIndex, column: columns.length },
  };

  // 6. Rows
  rows.forEach((rowData, rowIndex) => {
    const r = sheet.getRow(headerRowIndex + 1 + rowIndex);
    columns.forEach((col, colIndex) => {
      const cell = r.getCell(colIndex + 1);
      const val = col.value ? col.value(rowData) : rowData[col.key as keyof T];

      if (col.format === "text") {
        cell.value = val === null || val === undefined ? "" : String(val);
        cell.numFmt = "@";
        cell.alignment = { horizontal: "left" };
      } else if (col.format === "number") {
        cell.value = val !== null && val !== undefined ? Number(val) : "";
        cell.numFmt = "#,##0";
      } else if (col.format === "currency") {
        cell.value = val !== null && val !== undefined ? Number(val) : "";
        cell.numFmt = "\"SAR\" #,##0.00";
      } else if (col.format === "date") {
        // Basic date formatting, more complex Saudi specific could be added
        cell.value = val ? new Date(val as string | number | Date) : "";
        cell.numFmt = "dd/mm/yyyy hh:mm";
      } else {
        cell.value = val as string | number | null | undefined;
      }

      cell.border = {
        top: { style: "thin", color: { argb: "FFEEEEEE" } },
        left: { style: "thin", color: { argb: "FFEEEEEE" } },
        bottom: { style: "thin", color: { argb: "FFEEEEEE" } },
        right: { style: "thin", color: { argb: "FFEEEEEE" } },
      };
    });
  });

  // Write and Download
  const buffer = await workbook.xlsx.writeBuffer();
  const blob = new Blob([buffer], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  });
  const url = URL.createObjectURL(blob);

  const link = document.createElement("a");
  link.href = url;
  link.download = metadata.fileName;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

  setTimeout(() => {
    URL.revokeObjectURL(url);
  }, 100);
}
